apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    app: myapp

spec:
  ports:
    - port: 5432
      name: postgres-something
      targetPort: 5432
  selector:
    app: myapp
    name: postgres-pod