apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: myapp

spec:
  replicas: 1
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: myapp

    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
  selector:
    matchLabels:
      name: postgres-pod
      app: myapp
