apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: myapp

spec:
  ports:
    - port: 6379
      name: redis-something
      targetPort: 6379
  selector:
    app: myapp
    name: redis-pod