apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: myapp

spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379