apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: myapp

spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
    name: voting-app-pod
  type: LoadBalancer