apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: myapp

spec:
  replicas: 1
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: myapp

    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      name: worker-app-pod
      app: myapp
